'use strict';
const fs = require('fs');
const d = JSON.parse(fs.readFileSync('E:/PC/网站/data/site.json', 'utf8'));
console.log('SETTING_KEYS in settings:', Object.keys(d.settings).join(','));
console.log('\nplanLines keys:', Object.keys(d.settings.planLines || {}).join(','));
const yuezi = d.settings.planLines.yuezi;
console.log('\n--- yuezi stages ---');
console.log(JSON.stringify(yuezi.stages, null, 1));
console.log('\n--- yuezi tiers[0] keys ---');
console.log(Object.keys(yuezi.tiers[0]).join(','));
console.log('\n--- yuezi tiers ---');
console.log(JSON.stringify(yuezi.tiers.map(t => ({ key: t.key, name: t.name, tag: t.tag, img: t.img })), null, 1));
console.log('\n--- beiyun keys ---');
console.log(Object.keys(d.settings.planLines.beiyun).join(','));
console.log('beiyun stages:', JSON.stringify(d.settings.planLines.beiyun.stages || null));
console.log('\n--- contact 二维码引用 ---');
const contactHtml = d.pages && d.pages[0] && d.pages[0].body_html || '';
const m = contactHtml.match(/contact-qr[\s\S]{0,300}/);
console.log(m ? m[0] : 'N/A');
